version: '3.7'
services:

  zookeeper:
    image: zookeeper:3.8.0
    hostname: zookeeper
    container_name: zookeeper-run
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: 
      - running-sim

  kafka:
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    container_name: "kafka-run"
    ports:
      - "9092:9092"
    expose:
      - "9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-run:2181/kafka
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: kafka-run
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-run:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
    networks: 
      - running-sim

  pinot-controller:
    image: apachepinot/pinot:0.12.0-arm64
    command: "StartController -zkAddress zookeeper-run:2181 -dataDir /data"
    container_name: "pinot-controller-run"
    volumes:
      - ./config:/config
      - ./data-realtime:/data
      - ./input:/input
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
    networks: 
      - running-sim

  pinot-broker:
    image: apachepinot/pinot:0.12.0-arm64
    command: "StartBroker -zkAddress zookeeper-run:2181"
    restart: unless-stopped
    container_name: "pinot-broker-run"
    ports:
      - "8099:8099"
    depends_on:
      - pinot-controller
    networks: 
      - running-sim

  pinot-server:
    image: apachepinot/pinot:0.12.0-arm64
    command: "StartServer -zkAddress zookeeper-run:2181"
    restart: unless-stopped
    container_name: "pinot-server-run"
    depends_on:
      - pinot-broker
    networks: 
      - running-sim
networks:
  running-sim:
    name: running-sim